[shy]
	debug = false

[shy.window]
	title = 'Hello'

[shy.render]
	vsync = 'on' # 'off' or 'adaptive'
	msaa = 4 # 0 for disabling MSAA
	update_rate = 'auto' # 60.0
	lock_framerate      = false
	update_multiplicity = 1
	time_history_count  = 4
